src/account/urls.py
from django.contrib.auth import views as auth_views #built-in auth.
from django.urls import path
from .import views

app_name = 'account'

urlpatterns = [
    path('register/',views.signup,name='sign-up'),
    path('login/',auth_views.LoginView.as_view(template_name='account/login.html'), name='sign-in'),
    path('logout/',auth_views.LogoutView.as_view(),name='sign-out'),
    path('update/user/',views.UserUpdateView.as_view(),name='update_account'),
    # ajax validation - username
    path('server-side/validate/username/',views.validate_username,name='validate_username'),
    # password reset,change route
    path('reset/',auth_views.PasswordResetView.as_view(
    	template_name='account/password_reset.html',
    	email_template_name='account/password_reset_email.html',
    	subject_template_name='account/password_reset_subject.txt'),
    name = 'password_reset'),

    path('reset/done/',auth_views.PasswordResetDoneView.as_view(
    	template_name='account/password_reset_done.html'),
    name = 'password_reset_done'),

    path('reset/<str:uidb64>/<str:token>/',auth_views.PasswordResetConfirmView.as_view(
    	template_name='account/password_reset_confirm.html'),
    name = 'password_reset_confirm'),

    path('reset/complete/',auth_views.PasswordResetCompleteView.as_view(
    	template_name='account/password_reset_complete.html'),
    name = 'password_reset_complete'),

]

src/boards/urls.py
from django.urls import path
from . import views



app_name = 'boards'

urlpatterns = [
    # path('',
    # 	views.board_index,
    # 	name='board_index'),

    path('',
        views.BoardListView.as_view(),
        name='board_index'),
    
    # path('boards/<str:pk>/',
    # 	views.board_topics,
    # 	name='board_topics'),

    path('boards/<str:pk>/',
        views.BoardTopicsListView.as_view(),
        name='board_topics'),

    path('boards/<str:pk>/new/topic',
    	views.new_topic,
    	name='new_topic'),

    # path('boards/<str:board_pk>/topics/<str:topic_pk>/',
    # 	views.topic_posts_view,
    # 	name='topic_posts'),

    path('boards/<str:board_pk>/topics/<str:topic_pk>/',
        views.TopicPostListView.as_view(),
        name='topic_posts'),


    path('boards/<str:board_pk>/topics/<str:topic_pk>/reply/',
    	views.reply_topic,
    	name='reply_topic'),

    path('boards/<str:board_pk>/topics/<str:topic_pk>/posts/<str:post_pk>/edit/',
    	views.PostUpdateView.as_view(),
    	name='update_post'),

]

src/boards/models.py
import math
import uuid
# markdown utilities
from django.utils.html import mark_safe
from markdown import markdown

from django.conf import settings
from django.utils.text import Truncator
from django.db import models




class Board(models.Model):
	"""
	Board Model
	"""
	id   		= models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
	name 		= models.CharField(max_length=125,unique=True)
	description = models.TextField(max_length = 255)

	created		= models.DateTimeField(auto_now_add = True)
	updated		= models.DateTimeField(auto_now = True)


	class Meta:
		ordering = ['-created']
		verbose_name = 'Board'
		verbose_name_plural = 'Boards'


	def __str__(self):

		return self.name if self.name else None


	@property	
	def get_posts_count(self):

		return Post.objects.filter(topic__board = self).count()

	@property
	def get_last_post(self):

		return Post.objects.filter(topic__board = self).first()
	






class Topic(models.Model):
	"""
	Topic Model
	"""
	id   		= models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
	subject     = models.CharField(max_length=125)
	board       = models.ForeignKey(Board,related_name='topics',on_delete=models.SET_NULL,null=True)
	starter 	= models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE,related_name='user_topics')
	views 		= models.PositiveSmallIntegerField(default = 0) #viewers counter

	created		= models.DateTimeField(auto_now_add = True)
	updated		= models.DateTimeField(auto_now = True)


	class Meta:
		ordering = ['-created']
		verbose_name = 'Topic'
		verbose_name_plural = 'Topics'


	def __str__(self):
		return "{0} by {1}".format(self.subject,
			self.starter.username) if self.starter and self.subject else None


	def get_page_count(self):
		count = self.posts.count()
		pages = count/2 #pagination number
		return math.ceil(pages)


	def get_last_3_posts(self):

		return self.posts.all()[:3]



	def has_many_pages(self,count=None):
		if count is None:
			count = self.get_page_count()
		return count > 2


	def get_page_range(self):
		count = self.get_page_count()
		if self.has_many_pages(count):
			return range(1,3)
		return range(1,count + 1)




class Post(models.Model):
	"""
	Post Model
	"""
	id   		= models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
	message		= models.TextField(max_length=125)
	topic 		= models.ForeignKey(Topic,related_name='posts',on_delete=models.CASCADE)
	created_by  = models.ForeignKey(settings.AUTH_USER_MODEL,related_name='user_posts',on_delete=models.CASCADE)
	updated_by  = models.ForeignKey(settings.AUTH_USER_MODEL,related_name='+',null=True,on_delete=models.SET_NULL)

	created		= models.DateTimeField(auto_now_add = True)
	updated		= models.DateTimeField(auto_now = True)


	class Meta:
		ordering = ['-created']
		verbose_name = 'Post'
		verbose_name_plural = 'Posts'


	def __str__(self):
		message_truc_obj = Truncator(self.message)
		return message_truc_obj.chars(13)


	def get_message_as_markdown(self):
		return mark_safe(markdown(self.message,safe_mode='escape'))

src/boards/forms.py
from django import forms
from .import models



class NewTopicForm(forms.ModelForm):
	message = forms.CharField(
		widget=forms.Textarea(attrs={'rows':5,'placeholder':'What is on your mind bro ?'}),
		max_length=250,
		help_text="The max length of text is 250")

	class Meta:
		model  = models.Topic
		fields = ['subject','message']
	 



class PostForm(forms.ModelForm):

	class Meta:
		model = models.Post
		fields = ['message',]



# class EditPostForm(forms.ModelForm):

# 	class Meta:
# 		model = models.Post
# 		fields = ['message',]

src/boards/views.py
from django.utils import timezone
from django.db.models import Count
from django.urls import resolve,reverse
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render,redirect,get_object_or_404
from django.http import HttpResponse,HttpResponseRedirect

# Generic Views
from django.utils.decorators import method_decorator
from django.views.generic import UpdateView,ListView

from .forms import NewTopicForm,PostForm
from .models import Board,Topic,Post


# def board_index(request):

# 	context  = dict()
# 	boards = Board.objects.all()
# 	template = 'boards/index.html'

# 	context['boards'] = boards
# 	return render(request,template,context)


class BoardListView(ListView):

	model = Board #Board.objects.all()
	context_object_name = 'boards'#context['boards'] = boards
	template_name = 'boards/index.html' #template = 'boards/index.html'




# def board_topics(request,pk):

# 	context = dict()
# 	board = get_object_or_404(Board,id = pk)
# 	queryset = board.topics.annotate(replies = Count('posts') - 1)# (-1)exclude starter topics
# 	# print(queryset)

# 	# Pagination 

# 	page = request.GET.get('page',1)
# 	paginator = Paginator(queryset,10)#show X items per page

# 	try:
# 		topics = paginator.page(page)
# 	except PageNotAnInteger:
# 		#fallback to first page
# 		topics = paginator.page(1)
# 	except EmptyPage:
# 		#probabily user tries to add a page number in url
# 		#fall back to last page
# 		topics = paginator.page(paginator.num_pages)

# 	# end pagination scripts

# 	template = 'boards/topics.html'
# 	context['board'] = board
# 	context['topics'] = topics
# 	return render(request,template,context)




class BoardTopicsListView(ListView):

	model = Topic #Model to work on
	context_object_name = 'topics' #context['topics'] = topics
	template_name = 'boards/topics.html'
	paginate_by = 5


	def get_context_data(self,**kwargs):
		"""
		overrides context
		"""
		kwargs['board'] = self.board #context['board'] = board
		return super().get_context_data(**kwargs)


	def get_queryset(self):
		"""
		overrides queryset
		"""
		self.board = get_object_or_404(Board,pk=self.kwargs.get('pk'))
		queryset = self.board.topics.annotate(replies = Count('posts') - 1)
		return queryset












@login_required
def new_topic(request,pk):

	current_user = request.user

	context = dict()
	board = get_object_or_404(Board,id = pk)
	form =  NewTopicForm()
	if request.method == 'POST':
		form =  NewTopicForm(data = request.POST)
		if form.is_valid():
			topic_instance = form.save(commit=False)
			topic_instance.board = board
			topic_instance.starter = current_user
			topic_instance.save()

			post,_ = Post.objects.get_or_create(message = request.POST.get('message'),
				topic = topic_instance,
				created_by = current_user)
			return redirect('boards:board_topics',pk = board.pk)
		else:
			pass
			
	template = 'boards/new_topic.html'	
	context['board'] = board
	context['form'] = form
	return render(request,template,context)





# def topic_posts_view(request,board_pk,topic_pk):

# 	context  = dict()
# 	topic = get_object_or_404(Topic,id = topic_pk,board__id = board_pk)
# 	topic.views += 1
# 	topic.save()

# 	template = 'boards/topic_posts.html'
# 	context['topic'] = topic
# 	return render(request,template,context)
	

class TopicPostListView(ListView):

	model = Post
	context_object_name = 'posts'
	template_name = 'boards/topic_posts.html'
	paginate_by = 5


	def get_context_data(self,**kwargs):

		#Views counter for post details -- sweeet !!!
		session_key = 'viewed_topic_{}'.format(self.topic.pk)
		#check if post_id exists in session
		if not self.request.session.get(session_key,False):
			self.topic.views += 1
			self.topic.save() 
			self.request.session[session_key] = True # set user session post id to True (remember it)

		kwargs['topic'] = self.topic
		return super().get_context_data(**kwargs)


	def get_queryset(self):
		self.topic = get_object_or_404(Topic,
			board__pk=self.kwargs.get('board_pk'),
			pk=self.kwargs.get('topic_pk'))

		queryset = self.topic.posts.order_by('-created')
		return queryset







@login_required
def reply_topic(request,board_pk,topic_pk):
    topic = get_object_or_404(Topic,id = topic_pk,board__id = board_pk)
    if request.method == 'POST':
        form = PostForm(data = request.POST)
        if form.is_valid():
            post_instance = form.save(commit=False)
            post_instance.topic = topic
            post_instance.created_by = request.user
            post_instance.save()

            topic.update = timezone.now()
            topic.save()
            # Bug - Fix it !
            return redirect('boards:topic_posts', 
            	board_pk = str(board_pk),
            	topic_pk = str(topic_pk))

        else:
        	pass
    else:
        form = PostForm()
    return render(request, 'boards/reply_topic.html',{'topic': topic, 'form': form})





@method_decorator(login_required, name='dispatch')
class PostUpdateView(UpdateView):

	model = Post #model to perform action on
	fields = ('message',)#field to update in the model - (tuple,)
	template_name = 'boards/edit_post.html' #templete render page
	pk_url_kwarg = 'post_pk' # Post instance pk (to edit) ie. update_view(request,post_pk):pass
	context_object_name = 'post' # same as context = {'post':instance}


	def get_queryset(self):
		queryset = super().get_queryset() #override parent queryset that return Post.object.all()
		current_user = self.request.user
		user_only_post = queryset.filter(created_by = current_user)
		return user_only_post



	def form_valid(self,form):
		"""
		handling form validation - dev.
		"""
		post = form.save(commit = False)
		post.updated_by = self.request.user
		post.save()
		return redirect('boards:topic_posts', 
            	board_pk = post.topic.board.pk,
            	topic_pk = post.topic.pk)

src/boards/templates/boards/partials/_form.html
<!-- 
Re-useability of form rendered template
 -->

{% load widget_tweaks %}
    <!-- form body -->
      <!-- render error--->
        {% if form.non_field_errors %}
          <div class="alert alert-danger" role="alert">
            {% for error in form.non_field_errors %}
              <p{% if forloop.last %} class="mb-0"{% endif %}>{{ error }}</p>
            {% endfor %}
          </div>
        {% endif %}
      <!-- /render error--->
     {% for field in form %}
        <div class="form-group">
          {{ field.label_tag }}

          <!-- error fields style -->
          {% if form.is_bound %}<!-- a bound form fields -->
                {% if field.errors %}

                  {% render_field field class="form-control is-invalid" %}
                  {% for error in field.errors %}
                    <div class="invalid-feedback">
                      {{ error }}
                    </div>
                  {% endfor %}

                {% else %}
                  {% render_field field class="form-control is-valid" %}
                {% endif %}
          <!-- /error fields styles --> 
          {% else %} <!-- / bound form fields -->
                {% render_field field class="form-control" %} <!-- unbound form fields -->
          {% endif %}

          {% if field.help_text %}
            <small class="form-text text-muted">
              {{ field.help_text }} <!-- render help text -->
            </small>
          {% endif %}
        </div>
  {% endfor %}
    <!-- /form body -->

src/boards/templates/boards/partials/_nav.html
<nav class="navbar navbar-expand-sm navbar-dark bg-dark">
  <div class="container">
    <a class="navbar-brand" href="{% url 'boards:board_index' %}">Student Boards</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#mainMenu" aria-controls="mainMenu" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="mainMenu">
      {% if request.user.is_authenticated %}
        <ul class="navbar-nav ml-auto">
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="userMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              {% if request.user.is_authenticated %}{{ user.username }}{% endif %}
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userMenu">
              <a class="dropdown-item" href="{% url 'account:update_account' %}">My account</a>
              <a class="dropdown-item" href="#">Change password</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="{% url 'account:sign-out' %}">Log out</a>
            </div>
          </li>
        </ul>
      {% else %}
         <form class="form-inline ml-auto">
          <a href="{% url 'account:sign-in' %}" class="btn btn-outline-secondary">Log in</a>
          <a href="{% url 'account:sign-up' %}" class="btn btn-primary ml-2">Sign up</a>
        </form>
      {% endif %}
    </div>
  </div>
</nav>

src/boards/templates/boards/partials/_pagination.html
<!-- Optimize Pagination -->
{% if is_paginated %}
  <nav aria-label="Topics pagination" class="mb-4">
    <ul class="pagination justify-content-end  pagination-md">
      {% if page_obj.number > 1 %}
        <li class="page-item">
          <a class="page-link" href="?page=1">First</a>
        </li>
      {% else %}
        <li class="page-item disabled">
          <span class="page-link">First</span>
        </li>
      {% endif %}

      {% if page_obj.has_previous %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a>
        </li>
      {% else %}
        <li class="page-item disabled">
          <span class="page-link">Previous</span>
        </li>
      {% endif %}

      {% for page_num in paginator.page_range %}
        {% if page_obj.number == page_num %}
          <li class="page-item active">
            <span class="page-link">
              {{ page_num }}
              <span class="sr-only">(current)</span>
            </span>
          </li>
        {% elif page_num > page_obj.number|add:'-3' and page_num < page_obj.number|add:'3' %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a>
          </li>
        {% endif %}
      {% endfor %}

      {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a>
        </li>
      {% else %}
        <li class="page-item disabled">
          <span class="page-link">Next</span>
        </li>
      {% endif %}

      {% if page_obj.number != paginator.num_pages %}
        <li class="page-item">
          <a class="page-link" href="?page={{ paginator.num_pages }}">Last</a>
        </li>
      {% else %}
        <li class="page-item disabled">
          <span class="page-link">Last</span>
        </li>
      {% endif %}
    </ul>
  </nav>
{% endif %}