src/boards/urls.py
from django.urls import path
from . import views



app_name = 'boards'

urlpatterns = [
    # path('',
    # 	views.board_index,
    # 	name='board_index'),

    path('',
        views.BoardListView.as_view(),
        name='board_index'),
    
    # path('boards/<str:pk>/',
    # 	views.board_topics,
    # 	name='board_topics'),

    path('boards/<str:pk>/',
        views.BoardTopicsListView.as_view(),
        name='board_topics'),

    path('boards/<str:pk>/new/topic',
    	views.new_topic,
    	name='new_topic'),

    # path('boards/<str:board_pk>/topics/<str:topic_pk>/',
    # 	views.topic_posts_view,
    # 	name='topic_posts'),

    path('boards/<str:board_pk>/topics/<str:topic_pk>/',
        views.TopicPostListView.as_view(),
        name='topic_posts'),


    path('boards/<str:board_pk>/topics/<str:topic_pk>/reply/',
    	views.reply_topic,
    	name='reply_topic'),

    path('boards/<str:board_pk>/topics/<str:topic_pk>/posts/<str:post_pk>/edit/',
    	views.PostUpdateView.as_view(),
    	name='update_post'),

]

src/boards/models.py
import math
import uuid
# markdown utilities
from django.utils.html import mark_safe
from markdown import markdown

from django.conf import settings
from django.utils.text import Truncator
from django.db import models




class Board(models.Model):
	"""
	Board Model
	"""
	id   		= models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
	name 		= models.CharField(max_length=125,unique=True)
	description = models.TextField(max_length = 255)

	created		= models.DateTimeField(auto_now_add = True)
	updated		= models.DateTimeField(auto_now = True)


	class Meta:
		ordering = ['-created']
		verbose_name = 'Board'
		verbose_name_plural = 'Boards'


	def __str__(self):

		return self.name if self.name else None


	@property	
	def get_posts_count(self):

		return Post.objects.filter(topic__board = self).count()

	@property
	def get_last_post(self):

		return Post.objects.filter(topic__board = self).first()
	






class Topic(models.Model):
	"""
	Topic Model
	"""
	id   		= models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
	subject     = models.CharField(max_length=125)
	board       = models.ForeignKey(Board,related_name='topics',on_delete=models.SET_NULL,null=True)
	starter 	= models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE,related_name='user_topics')
	views 		= models.PositiveSmallIntegerField(default = 0) #viewers counter

	created		= models.DateTimeField(auto_now_add = True)
	updated		= models.DateTimeField(auto_now = True)


	class Meta:
		ordering = ['-created']
		verbose_name = 'Topic'
		verbose_name_plural = 'Topics'


	def __str__(self):
		return "{0} by {1}".format(self.subject,
			self.starter.username) if self.starter and self.subject else None


	def get_page_count(self):
		count = self.posts.count()
		pages = count/2 #pagination number
		return math.ceil(pages)


	def get_last_3_posts(self):

		return self.posts.all()[:3]



	def has_many_pages(self,count=None):
		if count is None:
			count = self.get_page_count()
		return count > 2


	def get_page_range(self):
		count = self.get_page_count()
		if self.has_many_pages(count):
			return range(1,3)
		return range(1,count + 1)




class Post(models.Model):
	"""
	Post Model
	"""
	id   		= models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
	message		= models.TextField(max_length=125)
	topic 		= models.ForeignKey(Topic,related_name='posts',on_delete=models.CASCADE)
	created_by  = models.ForeignKey(settings.AUTH_USER_MODEL,related_name='user_posts',on_delete=models.CASCADE)
	updated_by  = models.ForeignKey(settings.AUTH_USER_MODEL,related_name='+',null=True,on_delete=models.SET_NULL)

	created		= models.DateTimeField(auto_now_add = True)
	updated		= models.DateTimeField(auto_now = True)


	class Meta:
		ordering = ['-created']
		verbose_name = 'Post'
		verbose_name_plural = 'Posts'


	def __str__(self):
		message_truc_obj = Truncator(self.message)
		return message_truc_obj.chars(13)


	def get_message_as_markdown(self):
		return mark_safe(markdown(self.message,safe_mode='escape'))

src/boards/forms.py
from django import forms
from .import models



class NewTopicForm(forms.ModelForm):
	message = forms.CharField(
		widget=forms.Textarea(attrs={'rows':5,'placeholder':'What is on your mind bro ?'}),
		max_length=250,
		help_text="The max length of text is 250")

	class Meta:
		model  = models.Topic
		fields = ['subject','message']
	 



class PostForm(forms.ModelForm):

	class Meta:
		model = models.Post
		fields = ['message',]



# class EditPostForm(forms.ModelForm):

# 	class Meta:
# 		model = models.Post
# 		fields = ['message',]

src/boards/views.py
from django.utils import timezone
from django.db.models import Count
from django.urls import resolve,reverse
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render,redirect,get_object_or_404
from django.http import HttpResponse,HttpResponseRedirect

# Generic Views
from django.utils.decorators import method_decorator
from django.views.generic import UpdateView,ListView

from .forms import NewTopicForm,PostForm
from .models import Board,Topic,Post


# def board_index(request):

# 	context  = dict()
# 	boards = Board.objects.all()
# 	template = 'boards/index.html'

# 	context['boards'] = boards
# 	return render(request,template,context)


class BoardListView(ListView):

	model = Board #Board.objects.all()
	context_object_name = 'boards'#context['boards'] = boards
	template_name = 'boards/index.html' #template = 'boards/index.html'




# def board_topics(request,pk):

# 	context = dict()
# 	board = get_object_or_404(Board,id = pk)
# 	queryset = board.topics.annotate(replies = Count('posts') - 1)# (-1)exclude starter topics
# 	# print(queryset)

# 	# Pagination 

# 	page = request.GET.get('page',1)
# 	paginator = Paginator(queryset,10)#show X items per page

# 	try:
# 		topics = paginator.page(page)
# 	except PageNotAnInteger:
# 		#fallback to first page
# 		topics = paginator.page(1)
# 	except EmptyPage:
# 		#probabily user tries to add a page number in url
# 		#fall back to last page
# 		topics = paginator.page(paginator.num_pages)

# 	# end pagination scripts

# 	template = 'boards/topics.html'
# 	context['board'] = board
# 	context['topics'] = topics
# 	return render(request,template,context)




class BoardTopicsListView(ListView):

	model = Topic #Model to work on
	context_object_name = 'topics' #context['topics'] = topics
	template_name = 'boards/topics.html'
	paginate_by = 5


	def get_context_data(self,**kwargs):
		"""
		overrides context
		"""
		kwargs['board'] = self.board #context['board'] = board
		return super().get_context_data(**kwargs)


	def get_queryset(self):
		"""
		overrides queryset
		"""
		self.board = get_object_or_404(Board,pk=self.kwargs.get('pk'))
		queryset = self.board.topics.annotate(replies = Count('posts') - 1)
		return queryset












@login_required
def new_topic(request,pk):

	current_user = request.user

	context = dict()
	board = get_object_or_404(Board,id = pk)
	form =  NewTopicForm()
	if request.method == 'POST':
		form =  NewTopicForm(data = request.POST)
		if form.is_valid():
			topic_instance = form.save(commit=False)
			topic_instance.board = board
			topic_instance.starter = current_user
			topic_instance.save()

			post,_ = Post.objects.get_or_create(message = request.POST.get('message'),
				topic = topic_instance,
				created_by = current_user)
			return redirect('boards:board_topics',pk = board.pk)
		else:
			pass
			
	template = 'boards/new_topic.html'	
	context['board'] = board
	context['form'] = form
	return render(request,template,context)





# def topic_posts_view(request,board_pk,topic_pk):

# 	context  = dict()
# 	topic = get_object_or_404(Topic,id = topic_pk,board__id = board_pk)
# 	topic.views += 1
# 	topic.save()

# 	template = 'boards/topic_posts.html'
# 	context['topic'] = topic
# 	return render(request,template,context)
	

class TopicPostListView(ListView):

	model = Post
	context_object_name = 'posts'
	template_name = 'boards/topic_posts.html'
	paginate_by = 5


	def get_context_data(self,**kwargs):

		#Views counter for post details -- sweeet !!!
		session_key = 'viewed_topic_{}'.format(self.topic.pk)
		#check if post_id exists in session
		if not self.request.session.get(session_key,False):
			self.topic.views += 1
			self.topic.save() 
			self.request.session[session_key] = True # set user session post id to True (remember it)

		kwargs['topic'] = self.topic
		return super().get_context_data(**kwargs)


	def get_queryset(self):
		self.topic = get_object_or_404(Topic,
			board__pk=self.kwargs.get('board_pk'),
			pk=self.kwargs.get('topic_pk'))

		queryset = self.topic.posts.order_by('-created')
		return queryset







@login_required
def reply_topic(request,board_pk,topic_pk):
    topic = get_object_or_404(Topic,id = topic_pk,board__id = board_pk)
    if request.method == 'POST':
        form = PostForm(data = request.POST)
        if form.is_valid():
            post_instance = form.save(commit=False)
            post_instance.topic = topic
            post_instance.created_by = request.user
            post_instance.save()

            topic.update = timezone.now()
            topic.save()
            # Bug - Fix it !
            return redirect('boards:topic_posts', 
            	board_pk = str(board_pk),
            	topic_pk = str(topic_pk))

        else:
        	pass
    else:
        form = PostForm()
    return render(request, 'boards/reply_topic.html',{'topic': topic, 'form': form})





@method_decorator(login_required, name='dispatch')
class PostUpdateView(UpdateView):

	model = Post #model to perform action on
	fields = ('message',)#field to update in the model - (tuple,)
	template_name = 'boards/edit_post.html' #templete render page
	pk_url_kwarg = 'post_pk' # Post instance pk (to edit) ie. update_view(request,post_pk):pass
	context_object_name = 'post' # same as context = {'post':instance}


	def get_queryset(self):
		queryset = super().get_queryset() #override parent queryset that return Post.object.all()
		current_user = self.request.user
		user_only_post = queryset.filter(created_by = current_user)
		return user_only_post



	def form_valid(self,form):
		"""
		handling form validation - dev.
		"""
		post = form.save(commit = False)
		post.updated_by = self.request.user
		post.save()
		return redirect('boards:topic_posts', 
            	board_pk = post.topic.board.pk,
            	topic_pk = post.topic.pk)

src/boards/templates/boards/edit_post.html
{% extends 'boards/layout/base.html' %}

{% block title %} Post Edit- Student Board{% endblock %}


{% block breadcrumb %}
  <li class="breadcrumb-item"><a href="{% url 'boards:board_index' %}">Boards</a></li>
  <li class="breadcrumb-item"><a href="{% url 'boards:board_topics' post.topic.board.pk %}">{{ post.topic.board.name }}</a></li>
  <li class="breadcrumb-item"><a href="{% url 'boards:topic_posts' post.topic.board.pk post.topic.pk %}">{{ post.topic.subject }}</a></li>
  <li class="breadcrumb-item active">Edit post</li>
{% endblock %}

{% block wrapper %}
  <form method="post" class="mb-4" novalidate>
    {% csrf_token %}
    {% include 'boards/partials/_form.html' %}
    <button type="submit" class="btn btn-success">Save changes</button>
    <a href="{% url 'boards:topic_posts' post.topic.board.pk post.topic.pk %}" class="btn btn-outline-secondary" role="button">Cancel</a>
  </form>
{% endblock %}

src/boards/templates/boards/index.html
{% extends 'boards/layout/base.html' %}

{% block title %}Board{% endblock %}


{% block breadcrumb %}
    <li class="breadcrumb-item active">Boards</li>
{% endblock %}

{% block wrapper %}
       <table class="table">
        <thead class="thead-dark">
          <tr>
            <th>Board</th>
            <th>Posts</th>
            <th>Topics</th>
            <th>Last Post</th>
          </tr>
        </thead>
        <tbody>
          {% for board in boards %}
            <tr>
              <td>
                <a href="{% url 'boards:board_topics' board.pk %}">{{ board.name }}</a>
                <small class="text-muted d-block">{{ board.description }}</small>
              </td>
              <td class="align-middle">{{ board.get_posts_count }}</td>
              <td class="align-middle">{{ board.topics.count }}</td>
              <td class="align-middle">
                  {% if board.get_last_post %}
                  <small>
                    <a href="#">
                      By {{ board.get_last_post.created_by.username }} at {{ board.get_last_post.created }}
                    </a>
                  </small>
                  {% else %}
                  <small class="text-muted">
                    <em>No posts yet.</em>
                  </small>
                  {% endif %}
              </td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
{% endblock %}

src/boards/templates/boards/new_topic.html
{% extends 'boards/layout/base.html' %}

{% block title %} New Topic - Student Board{% endblock %}


{% block breadcrumb %}
		<li class="breadcrumb-item">
			<a href="{% url 'boards:board_index' %}">Boards</a>
		</li>
		<li class="breadcrumb-item active">
			<a href="{% url 'boards:board_topics' board.pk %}">{{ board.name }}</a>
		</li>
		<li class="breadcrumb-item active">New topic</li>
{% endblock %}

{% block wrapper %}

  <form method="post" action="{% url 'boards:new_topic' board.pk %}" novalidate="novalidate">
    {% csrf_token %}
      {% include 'boards/partials/_form.html' %}
    <button type="submit" class="btn btn-success">Post</button>
  </form>

{% endblock %}

src/boards/templates/boards/reply_topic.html
{% extends 'boards/layout/base.html' %}

{% load static %}

{% block title %}Post a reply - {{ request.user.username }} {% endblock %}

{% block breadcrumb %}
  <li class="breadcrumb-item"><a href="{% url 'boards:board_index' %}">Boards</a></li>
  <li class="breadcrumb-item"><a href="{% url 'boards:board_topics' topic.board.id %}">{{ topic.board.name }}</a></li>
  <li class="breadcrumb-item"><a href="{% url 'boards:topic_posts' topic.board.id topic.id %}">{{ topic.subject }}</a></li>
  <li class="breadcrumb-item active">Post a reply</li>
{% endblock %}

{% block wrapper %}

  <form method="post" class="mb-4">
    {% csrf_token %}
     {% include 'boards/partials/_form.html' %}
    <button type="submit" class="btn btn-success">Post a reply</button>
  </form>

  {% for post in topic.get_last_3_posts %}
    <div class="card mb-2">
      <div class="card-body p-3">
        <div class="row mb-3">
          <div class="col-6">
            <strong class="text-muted">{{ post.created_by.username }}</strong>
          </div>
          <div class="col-6 text-right">
            <small class="text-muted">{{ post.created }}</small>
          </div>
        </div>
        {{ post.get_message_as_markdown }}
      </div>
    </div>
  {% endfor %}

{% endblock %}

src/boards/templates/boards/topic_posts.html
{% extends 'boards/layout/base.html' %}

{% load static %}

{% block title %}{{ topic.subject }}{% endblock %}

{% block breadcrumb %}
  <li class="breadcrumb-item"><a href="{% url 'boards:board_index' %}">Boards</a></li>
  <li class="breadcrumb-item"><a href="{% url 'boards:board_topics' topic.board.pk %}">{{ topic.board.name }}</a></li>
  <li class="breadcrumb-item active">{{ topic.subject }}</li>
{% endblock %}

{% block wrapper %}


<div class="mb-4">
  <a href="{% url 'boards:reply_topic' topic.board.id topic.id  %}" class="btn btn-primary" role="button">Reply</a>
</div>

  {% for post in posts %}
    <div class="card mb-2 {% if forloop.first %}border-dark{% endif %}">
      <!-- First Post -->
      {% if forloop.first %}
          <div class="card-header text-white bg-dark py-2 px-3">{{ topic.subject }}</div>
      {% endif %}
      <!-- /First Post Style -->
      <div class="card-body p-3">
        <div class="row">
          <div class="col-2">
            <img src="{% static 'boards/images/avatar.png' %}" alt="{{ post.created_by.username }}" class="w-100">
            {% if post.created_by.user_posts.count %}
            <small>Posts: {{ post.created_by.user_posts.count }}</small>
            {% endif %}
          </div>
          <div class="col-10">
            <div class="row mb-3">
              <div class="col-6">
                <strong class="text-muted">{{ post.created_by.username }}</strong>
              </div>
              <div class="col-6 text-right">
                <small class="text-muted">{{ post.created }}</small>
              </div>
            </div>

            <!-- {{ post.message }} -->
            {{ post.get_message_as_markdown }}

            {% if post.created_by == request.user %}
              <div class="mt-3">
                <a href="{% url 'boards:update_post' post.topic.board.id post.topic.id post.id %}" 
                class="btn btn-primary btn-sm" role="button">Edit</a>
              </div>
            {% endif %}
          </div>
        </div>
      </div>
    </div>
  {% endfor %}
  
  {% include 'boards/partials/_pagination.html' %}

{% endblock %}

src/boards/templates/boards/topics.html
{% extends 'boards/layout/base.html' %}

{% load humanize %}

{% block title %}Board{% endblock %}

{% block breadcrumb %}
		<li class="breadcrumb-item"><a href="{% url 'boards:board_index' %}">Boards</a></li>
		<li class="breadcrumb-item active">{{ board.name }}</li>
{% endblock %}

{% block wrapper %}

  <div class="mb-4">
    <a href="{% url 'boards:new_topic' board.pk %}" class="btn btn-primary">New topic</a>
  </div>

  <table class="table">
    <thead class="thead-dark">
      <tr>
        <th>Topic</th>
        <th>Starter</th>
        <th>Replies</th>
        <th>Views</th>
        <th>Last Update</th>
      </tr>
    </thead>
    <tbody>
      {% for topic in topics %}
        <tr>
          <td><a href="{% url 'boards:topic_posts' topic.board.id topic.id %}">{{ topic.subject }}</a></td>
          <td>{{ topic.starter.username }}</td>
          <td>{{ topic.replies }}</td>
          <td>{{ topic.views }}</td>
          <td>{{ topic.updated|naturaltime }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
  <!-- pagination start -->
    <!--   {% if topics %}
      <nav aria-label="Topics pagination" class="mb-4">
        <ul class="pagination">
          {% if topics.has_previous %}
            <li class="page-item">
              <a class="page-link" href="?page={{ topics.previous_page_number }}">Previous</a>
            </li>
          {% else %}
            <li class="page-item disabled">
              <span class="page-link">Previous</span>
            </li>
          {% endif %}

          {% for page_num in topics.paginator.page_range %}
            {% if topics.number == page_num %}
              <li class="page-item active">
                <span class="page-link">
                  {{ page_num }}
                  <span class="sr-only">(current)</span>
                </span>
              </li>
            {% else %}
              <li class="page-item">
                <a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a>
              </li>
            {% endif %}
          {% endfor %}

          {% if topics.has_next %}
            <li class="page-item">
              <a class="page-link" href="?page={{ topics.next_page_number }}">Next</a>
            </li>
          {% else %}
            <li class="page-item disabled">
              <span class="page-link">Next</span>
            </li>
          {% endif %}
        </ul>
      </nav>
    {% endif %}
     -->

<!-- GCBV pagination -->
  {% include 'boards/partials/_pagination.html' %}
<!-- pagination end -->

{% endblock %}